#!/usr/bin/env python

import rospy
from sensor_msgs.msg import Image

import cv2
from cv_bridge import CvBridge, CvBridgeError
import numpy as np

if __name__ == '__main__':
	rospy.init_node('image_publisher')
	rospy.loginfo('Executing image publisher')
	pub = rospy.Publisher('image', Image, queue_size=10)
	r = rospy.Rate(0.2) 
	blank_image = np.zeros((240,320,3), np.uint8)
	blank_image[:,0:160] = (255,0,0)
	blank_image[:,160:320] = (0,255,0)
	msg = CvBridge().cv2_to_imgmsg(blank_image)
	while not rospy.is_shutdown():
	   pub.publish(msg)
	   r.sleep()
